# Clase 0: Práctica

In [54]:
#Librerias
import numpy as np

## Números Complejos y Amplitudes de Probabilidad


In [20]:
# Función básica: Operaciones elementales con números complejos en Python
def demostrar_aritmetica_compleja(a, b):
    # Definición z = a + ib
    z = complex(a, b)
    
    # Conjugado complejo z*
    z_conj = np.conjugate(z)
    
    # Módulo al cuadrado |z|^2
    modulo_cuadrado = np.abs(z)**2 #Cuidado con los errores punto flotante
    
    return z, z_conj, modulo_cuadrado

z, z_conj, mod_sq = demostrar_aritmetica_compleja(1, 1)
print(f"Número complejo z: {z}")
print(f"Conjugado z*: {z_conj}")
print(f"Módulo al cuadrado |z|^2: {mod_sq}")

Número complejo z: (1+1j)
Conjugado z*: (1-1j)
Módulo al cuadrado |z|^2: 2.0000000000000004


### Ejercicio: Verificación de Normalización

Un qubit se representa como un vector normalizado $|\psi\rangle = \alpha|0\rangle + \beta |1\rangle$, tal que $|\alpha|^2+|\beta|^2=1$. Verificar que el estado de superposición definido por el vector $|-\rangle=\frac{1}{\sqrt{2}}(|0\rangle - |1\rangle)$ es un estado cuántico válido y normalizado

In [48]:
def verificar_normalizacion_qubit(alpha, beta):
    # Cálculo de las probabilidades individuales
    prob_0 = np.abs(alpha)**2
    prob_1 = np.abs(beta)**2
    
    # Suma de probabilidades
    norma_total = prob_0 + prob_1
    
    print(f"Amplitud de |0>: {alpha:.4f}")
    print(f"Amplitud de |1>: {beta:.4f}")
    print(f"Probabilidad P(0): {prob_0:.4f}")
    print(f"Probabilidad P(1): {prob_1:.4f}")
    print(f"Norma total (debe ser 1.0): {norma_total:.4f}")
    
    # Tolerancia numérica para punto flotante
    es_valido = np.isclose(norma_total, 1.0)
    return es_valido

# Amplitudes para el estado |->
amplitud_0 = 1 / np.sqrt(2)
amplitud_1 = -1 / np.sqrt(2)

estado_valido = verificar_normalizacion_qubit(amplitud_0, amplitud_1)
print(f"¿Es un estado qubit válido?: {estado_valido}")

Amplitud de |0>: 0.7071
Amplitud de |1>: -0.7071
Probabilidad P(0): 0.5000
Probabilidad P(1): 0.5000
Norma total (debe ser 1.0): 1.0000
¿Es un estado qubit válido?: True


## Notación de Dirac y vectores de estado

In [40]:
def crear_ket_bra(elementos):
    """
    Se instancia el ket estrictamente como vector columna mediante reshape.
    El array de Python por su cuenta no es interpretado como una matriz columna, entonces al trasponer no van a haber cambios.
    Entonces, el reshape es necesario siempre que se vaya a usar el operador daga o la trasposición en general.

    """
    # Instanciación estricta como vector columna (d x 1)
    ket = np.array(elementos).reshape(-1, 1)
    #Se instancia así porque 
    
    # Generación del Bra con el operador daga (conjugado transpuesto)
    bra = ket.conj().T
    
    return ket, bra

ket_v, bra_v = crear_ket_bra([1, 1j])
print(f"Ket |v> con dimensión {ket_v.shape}:\n{ket_v}\n")
print(f"Bra <v| con dimensión {bra_v.shape}:\n{bra_v}")

Ket |v> con dimensión (2, 1):
[[1.+0.j]
 [0.+1.j]]

Bra <v| con dimensión (1, 2):
[[1.-0.j 0.-1.j]]


## Operaciones básicas
Las operaciones básicas sí están definidas en Python tal que manejan 1D arrays sin necesidad del reshape, pero igual tenerlo en mente.

In [53]:
# Operaciones básicas entre estados cuánticos
print("Producto Interno:")
print(f"<0|1> = {np.vdot(ket_0, ket_1)}")
print(f"<0|+> = {np.vdot(ket_0, ket_mas).real:.4f}\n")

print("Producto Tensorial:")
print(f"|00> = {np.kron(ket_0, ket_0)}")
print(f"|+-> = {np.round(np.kron(ket_mas, ket_menos), 4)}\n")

print("Producto Externo:")
print(f"|0><0| =\n{np.outer(ket_0, ket_0)}")
print(f"|+><+| =\n{np.round(np.outer(ket_mas, ket_mas), 4)}")


Producto Interno:
<0|1> = 0
<0|+> = 0.7071

Producto Tensorial:
|00> = [1 0 0 0]
|+-> = [ 0.5 -0.5  0.5 -0.5]

Producto Externo:
|0><0| =
[[1 0]
 [0 0]]
|+><+| =
[[0.5 0.5]
 [0.5 0.5]]


## Bases ortonormales y espacio del qubit

In [34]:
# Función básica: Definición de la base estándar
ket_0 = np.array([1,0])
ket_1 = np.array([0,1])


# Base de Hadamard a partir de la base estándar
ket_mas = (ket_0 + ket_1) / np.sqrt(2)
ket_menos = (ket_0 - ket_1) / np.sqrt(2)

print("Base Estándar:")
print(f"|0>:\n{ket_0}\n|1>:\n{ket_1}\n")
print("Base de Hadamard:")
print(f"|+>:\n{ket_mas}\n|->:\n{ket_menos}")

Base Estándar:
|0>:
[1 0]
|1>:
[0 1]

Base de Hadamard:
|+>:
[0.70710678 0.70710678]
|->:
[ 0.70710678 -0.70710678]


### Ejercicio: Cálculo de probabilidades

Si un sistema se prepara en el estado $|+\rangle$ y se mide en la base computacional $\{|0\rangle, |1\rangle\}$,
la probabilidad de observar un resultado particular se rige por la proyección del estado sobre el vector
de medición: $p_i = |\langle u_i | \psi \rangle|^2$. Calcule numéricamente las probabilidades de colapso
al medir $|+\rangle$ en la base estándar, demostrando la generación de aleatoriedad genuina.

In [38]:
def simular_medicion(estado_preparado, base_medicion):
    probabilidades = [] #Array vacío
    for vector_base in base_medicion:
        # Cálculo de la amplitud de probabilidad <base|estado>
        amplitud = np.vdot(vector_base, estado_preparado)
        # Probabilidad = |amplitud|^2
        probabilidad = np.abs(amplitud)**2
        probabilidades.append(probabilidad)
    return probabilidades

# El estado a medir es |+>
estado_psi = ket_mas

# Medimos en la base estándar {|0>, |1>}
base_estandar = [ket_0, ket_1]

probs = simular_medicion(estado_psi, base_estandar)
print(f"Probabilidad de colapso a |0>: {probs[0]:.4f}")
print(f"Probabilidad de colapso a |1>: {probs[1]:.4f}")

Probabilidad de colapso a |0>: 0.5000
Probabilidad de colapso a |1>: 0.5000
Esta distribución uniforme (50/50) ilustra el principio de aleatoriedad cuántica determinista.


Notar como el anterior resultado corresponde a lo esperado de la teoría para estados cuánticos puros

## Evolución y Matrices de Pauli

In [47]:
# Función básica: Definición de operadores unitarios matriciales
I = np.eye(2)
X = np.array([[0, 1], [1, 0]])                   # Inversión de bit (NOT)
Y = np.array([[0, -1j], [1j, 0]])                # Fase e inversión
Z = np.array([[1, 0], [0, -1]])                  # Inversión de fase
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)    # Hadamard

# Verificación de la condición de unitariedad para la matriz H (H^\dagger * H = I)
identidad_calculada = H.conj().T @ H #El simbolo @ es el producto tensorial
es_unitaria = np.allclose(identidad_calculada, I)

print(f"Matriz de Hadamard H:\n{H}")
print(f"\n¿Es H una matriz unitaria válida?: {es_unitaria}")

Matriz de Hadamard H:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

¿Es H una matriz unitaria válida?: True
